project:
  type: website

website:
  title: "GiuseppePeressotti.github.io"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: teaching.qmd
        text: "Teaching"
      - text: "Assignments"
        menu:
          - assign01.qmd
          - assign02.qmd
          - assign03.qmd
          - assign04.qmd
          - assign05.qmd
          - assign06.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual
